version: '3.8'

services:
  magasin1:
    build: .
    volumes:
      - shared-data:/app/data
    environment:
      - ROLE=Magasin
      - LOCATION=Magasin 1
    command: python app.py

  magasin2:
    build: .
    volumes:
      - shared-data:/app/data
    environment:
      - ROLE=Magasin
      - LOCATION=Magasin 2
    command: python app.py

  magasin3:
    build: .
    volumes:
      - shared-data:/app/data
    environment:
      - ROLE=Magasin
      - LOCATION=Magasin 3
    command: python app.py

  centre_logistique:
    build: .
    volumes:
      - shared-data:/app/data
    environment:
      - ROLE=Centre Logistique
      - LOCATION=Centre Logistique
    command: python app.py

  maison_mere:
    build: .
    volumes:
      - shared-data:/app/data
    environment:
      - ROLE=Maison mère
      - LOCATION=Maison mère
    command: python app.py

volumes:
  shared-data:
