version: '3.8'

services:
  auth-service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8000:5000"
    environment:
      - SERVICE_NAME=auth_service
  location_service:
    build:
      context: ./location_service
    container_name: location_service
    ports:
      - "8001:5000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=location_service

  product_service:
    build:
      context: ./product_service
    container_name: product_service
    ports:
      - "8002:5000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=product_service

  stock_service:
    build:
      context: ./stock_service
    container_name: stock_service
    ports:
      - "8003:5000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=stock_service

  sale_service:
    build:
      context: ./sale_service
    container_name: sale_service
    ports:
      - "8004:5000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=sale_service
    
  client_service:
    build:
      context: ./client_service
    container_name: client_service
    ports:
      - "8005:5000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=client_service

  cart_service:
    build:
      context: ./cart_service
    container_name: cart_service
    ports:
      - "8006:5000"
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=cart_service

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  load_balancer:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - location_service
      - product_service
      - stock_service
      - sale_service
      - client_service
      - cart_service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
