global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:5000']

  - job_name: 'location_service'
    static_configs:
      - targets: ['location_service:5000']

  - job_name: 'product_service'
    static_configs:
      - targets: ['product_service:5000']

  - job_name: 'stock_service'
    static_configs:
      - targets: ['stock_service:5000']

  - job_name: 'sale_service'
    static_configs:
      - targets: ['sale_service:5000']

  - job_name: 'cart_service'
    static_configs:
      - targets: ['cart_service:5000']