global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service_1:5000']

  - job_name: 'location_service'
    static_configs:
      - targets: ['location_service_1:5000', 'location_service_2:5000']

  - job_name: 'product_service'
    static_configs:
      - targets: ['product_service_1:5000', 'product_service_2:5000']

  - job_name: 'stock_service'
    static_configs:
      - targets: ['stock_service_1:5000']

  - job_name: 'sale_service'
    static_configs:
      - targets: ['sale_service_1:5000']

  - job_name: 'cart_service'
    static_configs:
      - targets: ['cart_service_1:5000']
