@startuml vueprocessus
actor Magasin
actor CentreLogistique
actor MaisonMere

Magasin --> CentreLogistique : Demande de stock
CentreLogistique --> Magasin : Approvisionnement
Magasin --> MaisonMere : Données de ventes
MaisonMere --> Magasin : Mises à jour produits
@enduml