@startuml cu
left to right direction
actor User

rectangle "Système Caisse" {
    usecase "S'authentifier" as UC1
    usecase "Consulter les produits" as UC2
    usecase "Vérifier le stock" as UC3
    usecase "Effectuer une vente" as UC4
    usecase "Créer une demande de réapprovisionnement" as UC5
    usecase "Creer un compte" as UC6
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6
@enduml
