@startuml depl
node "Deploiement Docker" {
    [NGINX]
    [KrakenD]
    [Prometheus]

    node "Auth Service" {
        [Auth API]
        file "auth.db (SQLite)"
    }

    node "Stock Service" {
        [Stock API]
        file "stock.db (SQLite)"
    }

    node "Sale Service" {
        [Sale API]
        file "sale.db (SQLite)"
    }

    node "Product Service" {
        [Product API]
        file "product.db (SQLite)"
    }

    node "Location Service" {
        [Location API]
        file "location.db (SQLite)"
    }
}

cloud "Poste client" as Client

Client --> [NGINX]
[NGINX] --> [KrakenD]

[KrakenD] --> [Auth API]
[KrakenD] --> [Stock API]
[KrakenD] --> [Sale API]
[KrakenD] --> [Product API]
[KrakenD] --> [Location API]

[Prometheus] --> [Auth API] : scrape /metrics
[Prometheus] --> [Stock API]
[Prometheus] --> [Sale API]
[Prometheus] --> [Product API]
[Prometheus] --> [Location API]
@enduml
