@startuml log
package "Auth Service" {
    [AuthAPI] --> [AuthLogic]
    [AuthLogic] --> file "auth.db (SQLite)"
}

package "Stock Service" {
    [StockAPI] --> [StockLogic]
    [StockLogic] --> file "stock.db (SQLite)"
}

package "Sale Service" {
    [SaleAPI] --> [SaleLogic]
    [SaleLogic] --> file "sale.db (SQLite)"
}

package "Product Service" {
    [ProductAPI] --> [ProductLogic]
    [ProductLogic] --> file "product.db (SQLite)"
}

package "Location Service" {
    [LocationAPI] --> [LocationLogic]
    [LocationLogic] --> file "location.db (SQLite)"
}
@enduml