@startuml diag_deploiement
node "Machine locale (Hôte Docker)" {
    node "Container: app" {
        component "Application Python"
        file "store.db (SQLite fichier)"
        note right of "store.db (SQLite fichier)" : Base de données locale\naccessible en lecture/écriture\nvia SQLAlchemy
    }
}
@enduml