name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/mon-api-flask

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Lint stock service
        working-directory: stock_service
        run: |
          pip install -r requirements.txt
          pip install pylint
          PYTHONPATH=. pylint .
      - name: Lint product service
        working-directory: product_service
        run: |
          pip install -r requirements.txt
          pip install pylint
          PYTHONPATH=. pylint .
      - name: Lint sale service
        working-directory: sale_service
        run: |
          pip install -r requirements.txt
          pip install pylint
          PYTHONPATH=. pylint .
      - name: Lint location_service
        working-directory: location_service
        run: |
          pip install -r requirements.txt
          pip install pylint
          PYTHONPATH=. pylint .
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run tests for location service
        working-directory: location_service
        run: |
          pip install -r requirements.txt
          pip install pytest
          PYTHONPATH=$(pwd) pytest tests

      # - name: Run tests for stock service
      #   working-directory: stock_service
      #   run: |
      #     pip install -r requirements.txt
      #     pip install pytest
      #     PYTHONPATH=$(pwd) pytest tests

      - name: Run tests for product service
        working-directory: product_service
        run: |
          pip install -r requirements.txt
          pip install pytest
          PYTHONPATH=$(pwd) pytest tests

      # - name: Run tests for sale service
      #   working-directory: sale_service
      #   run: |
      #     pip install -r requirements.txt
      #     pip install pytest
      #     PYTHONPATH=$(pwd) pytest tests

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # AUTH SERVICE
      - name: Build and push auth_service
        uses: docker/build-push-action@v5
        with:
          context: ./auth_service
          file: ./auth_service/Dockerfile
          push: true
          tags: liangtzai/auth_service:latest

      # SALE SERVICE
      - name: Build and push sale_service
        uses: docker/build-push-action@v5
        with:
          context: ./sale_service
          file: ./sale_service/Dockerfile
          push: true
          tags: liangtzai/sale_service:latest

      # STOCK SERVICE
      - name: Build and push stock_service
        uses: docker/build-push-action@v5
        with:
          context: ./stock_service
          file: ./stock_service/Dockerfile
          push: true
          tags: liangtzai/stock_service:latest

      # LOCATION SERVICE
      - name: Build and push location_service
        uses: docker/build-push-action@v5
        with:
          context: ./location_service
          file: ./location_service/Dockerfile
          push: true
          tags: liangtzai/location_service:latest

      # PRODUCT SERVICE
      - name: Build and push product_service
        uses: docker/build-push-action@v5
        with:
          context: ./product_service
          file: ./product_service/Dockerfile
          push: true
          tags: liangtzai/product_service:latest

      # CART SERVICE
      - name: Build and push cart_service
        uses: docker/build-push-action@v5
        with:
          context: ./cart_service
          file: ./cart_service/Dockerfile
          push: true
          tags: liangtzai/cart_service:latest